### ISSUE TITLE
Unable to extract aishell data 

### ISSUE THREAD

**Issue by YashBangera7** [kaituoxu/ListenAttendSpell#2]
I downloaded the data_aishell.tgz file from opensrl website. It showed to be around 15GB in size. Later on, when I tried to extract files from it, it displays an error that says : "Invalid Compressed Data: Unable to Inflate". I used WinZip for the purpose. Can someone please help me with this?
I can proceed only when I have extracted the data. Thanks in advance.

**Comment by kaituoxu** [comment]
Using `tar -xvzf xx.tgz`
