### ISSUE TITLE
can't run aishell_data_prep.sh on original data, organised the same way with aishell

### ISSUE THREAD

**Issue by MNCTTY** [kaituoxu/ListenAttendSpell#9]
Hello again!

Even if I didn't succeed with training and decoding stages on original dataset, I decided try to run run.sh on my own data (annotations in russian), but I organised it exactly the same way that aishell data organised.

I created dir rus_data with transcript and wav dirs inside. I put inside trancript dir txt file in format: filename-without-extention, space, transcription
In wav dir I created train, test and dev dirs, and puted inside them dirs with wavs.

After that I changed pathes in run.sh that aishell_data_prep.sh requires.

But run.sh throws the error: 
```
Stage 0: Data Preparation
Error: local/aishell_data_prep.sh requires two directory arguments
```

if I run separately aishell_data_prep.sh with 2 pathes I face the same error.

Do you have any ideas why is it? What should I change?

**Comment by kaituoxu** [comment]
`local/aishell_data_prep.sh` only works for aishell dataset, this script will generate `wav.scp, text, spk2utt, utt2spk`.
You need to generate `wav.scp, text, spk2utt, utt2spk` of your dataset by yourself, and this maybe the only part you need to do by yourself.

**Comment by MNCTTY** [comment]
yep, finally I managed to do all preparations with our data
but
running 'run.sh' I faced this error in one sub-script:
`utt2spk is not in sorted order when sorted first on speaker-id`

can you explain, please, what does it mean conceptually? and why is it important for training?

**Comment by MNCTTY** [comment]
I see, it sorted by dir name that containing files
but I don't really understand why data_prep.sh sort aishell data and don't sort by directories my data. I didn't change any part of it.

my utt2spk file
```
000000 audio_book_000000
000000 audio_book_000001
000000 audio_book_000002
000000 audio_book_000003
000001 audio_book_000000
000001 audio_book_000001
000001 audio_book_000002
000001 audio_book_000003
000002 audio_book_000000
000002 audio_book_000001
000002 audio_book_000002
000002 audio_book_000003
```

aishell utt2spk file

```
BAC009S0002W0122 S0002
BAC009S0002W0123 S0002
BAC009S0002W0124 S0002
BAC009S0002W0125 S0002
BAC009S0002W0126 S0002
...
```

**Comment by MNCTTY** [comment]
and for some reason I had this situation:
`utils/validate_data_dir.sh: empty file spk2utt`
this file is really empty as every other file in test and dev directory
in train directory everything is ok
as I understand all scripts are similar for these 3 repositories. Why does it generate empty files?

**Comment by MNCTTY** [comment]
ok I solved it all with adding dir name to the all filenames
but now a very ununderstandable error

`[Lengths are /tmp/kaldi.E11A/utts=5875 versus /tmp/kaldi.E11A/utts.utt2dur=3242]`
what does it mean and what's the problem???

**Comment by MNCTTY** [comment]
solved everything with renaming
